DROP TABLE mst_user;
CREATE TABLE mst_user
(
	  USER_ID VARCHAR(255) NOT NULL PRIMARY KEY
	, USER_PASSWORD VARCHAR(255) NOT NULL
	, USER_NAME VARCHAR(255)
	, USER_BIRTH VARCHAR(255)
	, USER_SEX VARCHAR(255)
	, USER_EMAIL VARCHAR(255) NOT NULL
	, USER_PHONE VARCHAR(255)
	, USER_ZIPCODE VARCHAR(255)
	, USER_ADDRESS1 VARCHAR(255)
	, USER_ADDRESS2 VARCHAR(255)
	, USER_ROLE VARCHAR(255) NOT NULL
	, USER_LOGIN_FAIL_CNT INT
	, USER_OAUTH_TYPE VARCHAR(255)
	, USER_BIZ_NO VARCHAR(255)
	, USER_BIZ_NAME VARCHAR(255)
	, REG_USER_ID VARCHAR(255) NOT NULL
	, REG_DATE DATETIME NOT NULL
	, UPD_USER_ID VARCHAR(255) NOT NULL
	, UPD_DATE DATETIME NOT NULL
) DEFAULT CHARACTER SET UTF8;
ALTER TABLE mst_user ADD COLUMN USER_POINT INT;

DROP TABLE mst_user_address;
CREATE TABLE mst_user_address
(
	  ADDRESS_ID INT not null AUTO_INCREMENT PRIMARY KEY
	, ADDRESS_USER_ID VARCHAR(255) NOT NULL
	, ADDRESS_USER_PHONE VARCHAR(255)
	, ADDRESS_USER_ZIPCODE VARCHAR(255)
	, ADDRESS_USER_ADDRESS1 VARCHAR(255)
	, ADDRESS_USER_ADDRESS2 VARCHAR(255)
	, ADDRESS_USER_NAME VARCHAR(255)
	, REG_USER_ID VARCHAR(255) NOT NULL
	, REG_DATE DATETIME NOT NULL
	, UPD_USER_ID VARCHAR(255) NOT NULL
	, UPD_DATE DATETIME NOT NULL
   , FOREIGN KEY(ADDRESS_USER_ID) REFERENCES mst_user(USER_ID) ON DELETE CASCADE
) DEFAULT CHARACTER SET UTF8;

DROP TABLE mst_login_token;
CREATE TABLE mst_login_token
(
	  LOGIN_TOKEN_SERIES VARCHAR(255) NOT NULL PRIMARY KEY
	, LOGIN_TOKEN_USERNAME VARCHAR(255) NOT NULL
	, LOGIN_TOKEN VARCHAR(255) NOT NULL
	, LOGIN_TOKEN_LAST_USED VARCHAR(255) NOT NULL
	, REG_USER_ID VARCHAR(255) NOT NULL
	, REG_DATE DATETIME NOT NULL
	, UPD_USER_ID VARCHAR(255) NOT NULL
	, UPD_DATE DATETIME NOT NULL
) DEFAULT CHARACTER SET UTF8;

DROP TABLE mst_coupon;
CREATE TABLE mst_coupon
(
	  COUPON_CODE VARCHAR(255) NOT NULL PRIMARY KEY
	, COUPON_NAME VARCHAR(255) NOT NULL
	, COUPON_EXPLN VARCHAR(255) NOT NULL
	, COUPON_TYPE VARCHAR(10) NOT NULL
	, COUPON_AMT INT NOT NULL
	, COUPON_SDATE VARCHAR(10) NOT NULL
	, COUPON_EDATE VARCHAR(10) NOT NULL
	, REG_USER_ID VARCHAR(255) NOT NULL
	, REG_DATE DATETIME NOT NULL
	, UPD_USER_ID VARCHAR(255) NOT NULL
	, UPD_DATE DATETIME NOT NULL
) DEFAULT CHARACTER SET UTF8;

DROP TABLE mst_category;
CREATE TABLE mst_category (
	  CATEGORY_ID INT NOT NULL AUTO_INCREMENT
	, CATEGORY_PARENT INT
	, CATEGORY_DEPTH INT
	, CATEGORY_NAME VARCHAR(255)
	, CATEGORY_IMG VARCHAR(255)
	, REG_USER_ID VARCHAR(255) NOT NULL
	, REG_DATE DATETIME NOT NULL
	, UPD_USER_ID VARCHAR(255) NOT NULL
	, UPD_DATE DATETIME NOT NULL
	, PRIMARY KEY(CATEGORY_ID)
) DEFAULT CHARACTER SET UTF8;

DROP TABLE mst_notifi;
CREATE TABLE mst_notifi (
	  NOTIFI_ID INT NOT NULL AUTO_INCREMENT
	, NOTIFI_TYPE VARCHAR(10)
	, NOTIFI_TITLE VARCHAR(255)
	, NOTIFI_TEXT TEXT
	, NOTIFI_BANNER_IMG VARCHAR(255)
	, NOTIFI_MAIN_IMG VARCHAR(255)
	, NOTIFI_START_DT VARCHAR(10)
	, NOTIFI_END_DT VARCHAR(10)
	, REG_USER_ID VARCHAR(255) NOT NULL
	, REG_DATE DATETIME NOT NULL
	, UPD_USER_ID VARCHAR(255) NOT NULL
	, UPD_DATE DATETIME NOT NULL
	, PRIMARY KEY(NOTIFI_ID)
) DEFAULT CHARACTER SET UTF8;

DROP TABLE user_coupon;
CREATE TABLE user_coupon
(
	  USER_ID VARCHAR(255) NOT NULL
	, COUPON_CODE VARCHAR(255) NOT NULL
	, REG_USER_ID VARCHAR(255) NOT NULL
	, REG_DATE DATETIME NOT NULL
	, UPD_USER_ID VARCHAR(255) NOT NULL
	, UPD_DATE DATETIME NOT NULL
	, PRIMARY KEY(USER_ID, COUPON_CODE)
	, FOREIGN KEY(USER_ID) REFERENCES mst_user(USER_ID) ON DELETE CASCADE
	, FOREIGN KEY(COUPON_CODE) REFERENCES mst_coupon(COUPON_CODE) ON DELETE CASCADE
) DEFAULT CHARACTER SET UTF8;

DROP TABLE user_point_his;
CREATE TABLE user_point_his
(
	  POINT_USER_ID VARCHAR(255) NOT NULL
	, POINT_ID INT NOT NULL
	, POINT_NUM INT NOT NULL
	, POINT_REASON VARCHAR(255) NOT NULL
	, POINT_EXPLN VARCHAR(255) NOT NULL
	, REG_USER_ID VARCHAR(255) NOT NULL
	, REG_DATE DATETIME NOT NULL
	, UPD_USER_ID VARCHAR(255) NOT NULL
	, UPD_DATE DATETIME NOT NULL
	, PRIMARY KEY(POINT_USER_ID, POINT_ID)
	, FOREIGN KEY(POINT_USER_ID) REFERENCES mst_user(USER_ID) ON DELETE CASCADE
) DEFAULT CHARACTER SET UTF8;

DROP TABLE user_qna;
CREATE TABLE user_qna
(
	  QNA_USER_ID VARCHAR(255) NOT NULL
	, QNA_ID INT NOT NULL
	, QNA_QUESTION TEXT
	, QNA_ANSWER TEXT
	, QNA_ANSWER_YN VARCHAR(1)
	, REG_USER_ID VARCHAR(255) NOT NULL
	, REG_DATE DATETIME NOT NULL
	, UPD_USER_ID VARCHAR(255) NOT NULL
	, UPD_DATE DATETIME NOT NULL
	, PRIMARY KEY(QNA_USER_ID, QNA_ID)
	, FOREIGN KEY(QNA_USER_ID) REFERENCES mst_user(USER_ID) ON DELETE CASCADE
) DEFAULT CHARACTER SET UTF8;

DROP TABLE sel_item;
CREATE TABLE sel_item
(
	  SEL_USER_ID VARCHAR(255) NOT NULL
	, SEL_ITEM_ID VARCHAR(255) NOT NULL
	, SEL_ITEM_NAME VARCHAR(255)
	, SEL_CATEGORY_ID INT
	, SEL_MINI_IMG VARCHAR(255)
	, SEL_MAIN_IMG VARCHAR(255)
	, SEL_EXPLN TEXT
	, SEL_ITEM_PRICE INT
	, SEL_DEIL_PRICE INT
	, SEL_STAR_POINT FLOAT
	, SEL_SALE_COUNT INT
	, SEL_HEART_COUNT INT
	, SEL_STOCK_COUNT INT
	, REG_USER_ID VARCHAR(255) NOT NULL
	, REG_DATE DATETIME NOT NULL
	, UPD_USER_ID VARCHAR(255) NOT NULL
	, UPD_DATE DATETIME NOT NULL
	, PRIMARY KEY(SEL_USER_ID, SEL_ITEM_ID)
	, FOREIGN KEY(SEL_USER_ID) REFERENCES mst_user(USER_ID) ON DELETE CASCADE
	, FOREIGN KEY(SEL_CATEGORY_ID) REFERENCES mst_category(CATEGORY_ID) ON DELETE CASCADE
) DEFAULT CHARACTER SET UTF8;
ALTER TABLE sel_item ADD COLUMN SEL_STAR_POINT_AVG DOUBLE;
ALTER TABLE sel_item ADD COLUMN SEL_STAR_POINT_CNT INT;

DROP TABLE user_item_qna;
CREATE TABLE user_item_qna
(
	  ITEM_QNA_STORE_ID VARCHAR(255) NOT NULL
	, ITEM_QNA_ITEM_ID VARCHAR(255) NOT NULL
	, ITEM_QNA_USER_ID VARCHAR(255) NOT NULL
	, ITEM_QNA_ID INT NOT NULL
	, ITEM_QNA_QUESTION TEXT
	, ITEM_QNA_ANSWER TEXT
	, ITEM_QNA_ANSWER_YN VARCHAR(1)
	, REG_USER_ID VARCHAR(255) NOT NULL
	, REG_DATE DATETIME NOT NULL
	, UPD_USER_ID VARCHAR(255) NOT NULL
	, UPD_DATE DATETIME NOT NULL
	, PRIMARY KEY(ITEM_QNA_STORE_ID, ITEM_QNA_ITEM_ID, ITEM_QNA_USER_ID, ITEM_QNA_ID)
	, FOREIGN KEY(ITEM_QNA_USER_ID) REFERENCES mst_user(USER_ID) ON DELETE CASCADE
) DEFAULT CHARACTER SET UTF8;
ALTER TABLE user_item_qna ADD CONSTRAINT FOREIGN KEY (ITEM_QNA_STORE_ID, ITEM_QNA_ITEM_ID) REFERENCES sel_item(SEL_USER_ID, SEL_ITEM_ID);

DROP TABLE sel_item_stock;
CREATE TABLE sel_item_stock
(
	  STOCK_USER_ID VARCHAR(255) NOT NULL
	, STOCK_ITEM_ID VARCHAR(255) NOT NULL
	, STOCK_DT VARCHAR(10) NOT NULL
	, STOCK_ID INT NOT NULL
	, STOCK_QTY INT
	, STOCK_EXPLN VARCHAR(255)
	, REG_USER_ID VARCHAR(255) NOT NULL
	, REG_DATE DATETIME NOT NULL
	, UPD_USER_ID VARCHAR(255) NOT NULL
	, UPD_DATE DATETIME NOT NULL
	, PRIMARY KEY(STOCK_USER_ID, STOCK_ITEM_ID, STOCK_DT, STOCK_ID)
) DEFAULT CHARACTER SET UTF8;
ALTER TABLE sel_item_stock ADD CONSTRAINT FOREIGN KEY (STOCK_USER_ID, STOCK_ITEM_ID) REFERENCES sel_item(SEL_USER_ID, SEL_ITEM_ID);

DROP TABLE user_order;
CREATE TABLE user_order
(
	  ORD_USER_ID VARCHAR(255) NOT NULL
	, ORD_DT VARCHAR(10) NOT NULL
	, ORD_ID INT NOT NULL
	, ORD_ADDRESS VARCHAR(255)
	, ORD_NAME VARCHAR(255)
	, ORD_PHONE VARCHAR(255)
	, ORD_TOT_AMT INT
	, ORD_COU_DC INT
	, ORD_POI_DC INT
	, ORD_DEL_AMT INT
	, ORD_NET_AMT INT
	, REG_USER_ID VARCHAR(255) NOT NULL
	, REG_DATE DATETIME NOT NULL
	, UPD_USER_ID VARCHAR(255) NOT NULL
	, UPD_DATE DATETIME NOT NULL
	, PRIMARY KEY(ORD_USER_ID, ORD_DT, ORD_ID)
	, FOREIGN KEY(ORD_USER_ID) REFERENCES mst_user(USER_ID) ON DELETE CASCADE
) DEFAULT CHARACTER SET UTF8;

DROP TABLE sel_order;
CREATE TABLE sel_order
(
	  ORD_USER_ID VARCHAR(255) NOT NULL
	, ORD_DT VARCHAR(10) NOT NULL
	, ORD_ID INT NOT NULL
	, USER_ORD_USER_ID VARCHAR(255) NOT NULL
	, USER_ORD_DT VARCHAR(10) NOT NULL
	, USER_ORD_ID INT NOT NULL
	, ORD_STATUS VARCHAR(1)
	, ORD_INVOICE VARCHAR(255)
	, ORD_TOT_AMT INT
	, ORD_DEL_AMT INT
	, REG_USER_ID VARCHAR(255) NOT NULL
	, REG_DATE DATETIME NOT NULL
	, UPD_USER_ID VARCHAR(255) NOT NULL
	, UPD_DATE DATETIME NOT NULL
	, PRIMARY KEY(ORD_USER_ID, ORD_DT, ORD_ID)
	, FOREIGN KEY(ORD_USER_ID) REFERENCES mst_user(USER_ID) ON DELETE CASCADE
) DEFAULT CHARACTER SET UTF8;
ALTER TABLE sel_order ADD CONSTRAINT FOREIGN KEY (USER_ORD_USER_ID, USER_ORD_DT, USER_ORD_ID) REFERENCES user_order(ORD_USER_ID, ORD_DT, ORD_ID);

DROP TABLE sel_order_item;
CREATE TABLE sel_order_item
(
	  ORD_USER_ID VARCHAR(255) NOT NULL
	, ORD_DT VARCHAR(10) NOT NULL
	, ORD_ID INT NOT NULL
	, ITEM_USER_ID VARCHAR(255) NOT NULL
	, ITEM_ID VARCHAR(255) NOT NULL
	, ORD_CNT INT
	, ORD_AMT INT
	, REG_USER_ID VARCHAR(255) NOT NULL
	, REG_DATE DATETIME NOT NULL
	, UPD_USER_ID VARCHAR(255) NOT NULL
	, UPD_DATE DATETIME NOT NULL
	, PRIMARY KEY(ORD_USER_ID, ORD_DT, ORD_ID, ITEM_USER_ID, ITEM_ID)
) DEFAULT CHARACTER SET UTF8;
ALTER TABLE sel_order_item ADD ITEM_REVIEW_YN VARCHAR(1);
ALTER TABLE sel_order_item ADD CONSTRAINT FOREIGN KEY (ORD_USER_ID, ORD_DT, ORD_ID) REFERENCES sel_order(ORD_USER_ID, ORD_DT, ORD_ID);
ALTER TABLE sel_order_item ADD CONSTRAINT FOREIGN KEY (ITEM_USER_ID, ITEM_ID) REFERENCES sel_item(SEL_USER_ID, SEL_ITEM_ID);

DROP TABLE sel_order_sale;
CREATE TABLE sel_order_sale
(
	  ORD_USER_ID VARCHAR(255) NOT NULL
	, ORD_DT VARCHAR(10) NOT NULL
	, ORD_ID INT NOT NULL
	, SALE_CNT INT
	, SALE_AMT INT
	, REG_USER_ID VARCHAR(255) NOT NULL
	, REG_DATE DATETIME NOT NULL
	, UPD_USER_ID VARCHAR(255) NOT NULL
	, UPD_DATE DATETIME NOT NULL
	, PRIMARY KEY(ORD_USER_ID, ORD_DT, ORD_ID)
) DEFAULT CHARACTER SET UTF8;
ALTER TABLE sel_order_sale ADD CONSTRAINT FOREIGN KEY (ORD_USER_ID, ORD_DT, ORD_ID) REFERENCES sel_order(ORD_USER_ID, ORD_DT, ORD_ID);

DROP TABLE sel_item_review;
CREATE TABLE sel_item_review
(
	  REVIEW_STORE_ID VARCHAR(255) NOT NULL
	, REVIEW_ITEM_ID VARCHAR(255) NOT NULL
	, REVIEW_DT VARCHAR(10) NOT NULL
	, REVIEW_ID INT NOT NULL
	, REVIEW_USER_ID VARCHAR(255) NOT NULL
	, REVIEW_STAR_POINT INT
	, REVIEW_TEXT TEXT
	, REG_USER_ID VARCHAR(255) NOT NULL
	, REG_DATE DATETIME NOT NULL
	, UPD_USER_ID VARCHAR(255) NOT NULL
	, UPD_DATE DATETIME NOT NULL
	, PRIMARY KEY(REVIEW_STORE_ID, REVIEW_ITEM_ID, REVIEW_DT, REVIEW_ID)
) DEFAULT CHARACTER SET UTF8;
ALTER TABLE sel_item_review ADD CONSTRAINT FOREIGN KEY (REVIEW_STORE_ID, REVIEW_ITEM_ID) REFERENCES sel_item(SEL_USER_ID, SEL_ITEM_ID);
ALTER TABLE sel_item_review ADD CONSTRAINT FOREIGN KEY (REVIEW_USER_ID) REFERENCES mst_user(USER_ID);

DROP TABLE user_cart;
CREATE TABLE user_cart
(
	  CART_USER_ID VARCHAR(255) NOT NULL
	, CART_STORE_ID VARCHAR(255) NOT NULL
	, CART_ITEM_ID VARCHAR(255) NOT NULL
	, CART_CNT INT NOT NULL
	, REG_USER_ID VARCHAR(255) NOT NULL
	, REG_DATE DATETIME NOT NULL
	, UPD_USER_ID VARCHAR(255) NOT NULL
	, UPD_DATE DATETIME NOT NULL
	, PRIMARY KEY(CART_USER_ID, CART_STORE_ID, CART_ITEM_ID)
	, FOREIGN KEY(CART_USER_ID) REFERENCES mst_user(USER_ID) ON DELETE CASCADE
) DEFAULT CHARACTER SET UTF8;
ALTER TABLE user_cart ADD CONSTRAINT FOREIGN KEY (CART_STORE_ID, CART_ITEM_ID) REFERENCES sel_item(SEL_USER_ID, SEL_ITEM_ID);

-- 쿠폰 복사
DELIMITER $$
CREATE OR replace PROCEDURE INSERT_COUPON()
BEGIN
	DECLARE i INT default 10;
	while (i<99) do
	INSERT INTO mst_coupon(COUPON_CODE, COUPON_NAME, COUPON_EXPLN, COUPON_TYPE, COUPON_AMT, COUPON_SDATE, COUPON_EDATE, REG_USER_ID, REG_DATE, UPD_USER_ID, UPD_DATE)
	VALUE ('113123'+i, '1', '1', '1', 1, '20230901', '20230904', 'test', NOW(), 'test', NOW());
	SET i = i + 1;
	END while;
END$$
DELIMITER ;
CALL INSERT_COUPON();

-- 날짜지난 쿠폰 삭제
DELIMITER $$
CREATE OR replace PROCEDURE PROCEDURE_EXPIRED_COUPON()
BEGIN

DELETE
  FROM MST_COUPON
 WHERE COUPON_EDATE < DATE_FORMAT(NOW(), '%Y%m%d');

END$$
DELIMITER ;
CALL PROCEDURE_EXPIRED_COUPON();;;